/**
 * Icon Category Localization Mappings
 * Maps icon category keys to localized display names for tooltips and UI
 */

type SupportedLanguage = 'en' | 'es' | 'de' | 'fr' | 'it' | 'ja' | 'pt_BR' | 'ko' | 'hi' | 'tr' | 'ar';

type IconCategoryLocalizations = {
    [key: string]: {
        en: string;
        es: string;
        de: string;
        fr: string;
        it: string;
        ja: string;
        pt_BR: string;
        ko: string;
        hi: string;
        tr: string;
        ar: string;
    };
};
export const ICON_CATEGORY_LOCALIZATIONS: IconCategoryLocalizations = {
    "alcoholic-beverage": {
        en: "Alcoholic Beverage",
        es: "Bebida Alcohólica",
        de: "Alkoholisches Getränk",
        fr: "Boisson Alcoolisée",
        it: "Bevanda Alcolica",
        ja: "アルコール飲料",
        pt_BR: "Bebida Alcoólica",
        ko: "알코올 음료",
        hi: "मादक पेय",
        tr: "Alkollü İçecek",
        ar: "مشروب كحولي"
    },
    "baby-clothes": {
        en: "Baby Clothes",
        es: "Ropa de Bebé",
        de: "Babykleidung",
        fr: "Vêtements de Bébé",
        it: "Vestiti per Bambini",
        ja: "ベビー服",
        pt_BR: "Roupas de Bebê",
        ko: "아기 옷",
        hi: "बच्चों के कपड़े",
        tr: "Bebek Kıyafetleri",
        ar: "ملابس الأطفال"
    },
    "backpack": {
        en: "Backpack",
        es: "Mochila",
        de: "Rucksack",
        fr: "Sac à Dos",
        it: "Zaino",
        ja: "バックパック",
        pt_BR: "Mochila",
        ko: "백팩",
        hi: "बैकपैक",
        tr: "Sırt Çantası",
        ar: "حقيبة ظهر"
    },
    "bathroom": {
        en: "Bathroom",
        es: "Baño",
        de: "Badezimmer",
        fr: "Salle de Bain",
        it: "Bagno",
        ja: "バスルーム",
        pt_BR: "Banheiro",
        ko: "욕실",
        hi: "बाथरूम",
        tr: "Banyo",
        ar: "حمام"
    },
    "beanie": {
        en: "Beanie",
        es: "Gorro",
        de: "Mütze",
        fr: "Bonnet",
        it: "Berretto",
        ja: "ビーニー",
        pt_BR: "Gorro",
        ko: "비니",
        hi: "टोपी",
        tr: "Bere",
        ar: "قبعة صوفية"
    },
    "beauty-and-selfcare": {
        en: "Beauty & Self Care",
        es: "Belleza y Cuidado Personal",
        de: "Schönheit & Körperpflege",
        fr: "Beauté & Soins Personnels",
        it: "Bellezza & Cura Personale",
        ja: "美容・セルフケア",
        pt_BR: "Beleza e Cuidados Pessoais",
        ko: "뷰티 & 셀프케어",
        hi: "सौंदर्य और स्वयं की देखभाल",
        tr: "Güzellik ve Kişisel Bakım",
        ar: "الجمال والعناية الشخصية"
    },
    "bedroom": {
        en: "Bedroom",
        es: "Dormitorio",
        de: "Schlafzimmer",
        fr: "Chambre",
        it: "Camera da Letto",
        ja: "ベッドルーム",
        pt_BR: "Quarto",
        ko: "침실",
        hi: "शयनकक्ष",
        tr: "Yatak Odası",
        ar: "غرفة النوم"
    },
    "belt": {
        en: "Belt",
        es: "Cinturón",
        de: "Gürtel",
        fr: "Ceinture",
        it: "Cintura",
        ja: "ベルト",
        pt_BR: "Cinto",
        ko: "벨트",
        hi: "बेल्ट",
        tr: "Kemer",
        ar: "حزام"
    },
    "bicycle": {
        en: "Bicycle",
        es: "Bicicleta",
        de: "Fahrrad",
        fr: "Vélo",
        it: "Bicicletta",
        ja: "自転車",
        pt_BR: "Bicicleta",
        ko: "자전거",
        hi: "साइकिल",
        tr: "Bisiklet",
        ar: "دراجة هوائية"
    },
    "board-games": {
        en: "Board Games",
        es: "Juegos de Mesa",
        de: "Brettspiele",
        fr: "Jeux de Société",
        it: "Giochi da Tavolo",
        ja: "ボードゲーム",
        pt_BR: "Jogos de Tabuleiro",
        ko: "보드게임",
        hi: "बोर्ड गेम्स",
        tr: "Masa Oyunları",
        ar: "ألعاب الطاولة"
    },
    "book": {
        en: "Book",
        es: "Libro",
        de: "Buch",
        fr: "Livre",
        it: "Libro",
        ja: "本",
        pt_BR: "Livro",
        ko: "책",
        hi: "किताब",
        tr: "Kitap",
        ar: "كتاب"
    },
    "bracelet": {
        en: "Bracelet",
        es: "Pulsera",
        de: "Armband",
        fr: "Bracelet",
        it: "Braccialetto",
        ja: "ブレスレット",
        pt_BR: "Pulseira",
        ko: "팔찌",
        hi: "कंगन",
        tr: "Bilezik",
        ar: "سوار"
    },
    "cabinet": {
        en: "Cabinet",
        es: "Gabinete",
        de: "Schrank",
        fr: "Armoire",
        it: "Mobile",
        ja: "キャビネット",
        pt_BR: "Armário",
        ko: "캐비닛",
        hi: "अलमारी",
        tr: "Dolap",
        ar: "خزانة"
    },
    "camera": {
        en: "Camera",
        es: "Cámara",
        de: "Kamera",
        fr: "Appareil Photo",
        it: "Fotocamera",
        ja: "カメラ",
        pt_BR: "Câmera",
        ko: "카메라",
        hi: "कैमरा",
        tr: "Kamera",
        ar: "كاميرا"
    },
    "candy": {
        en: "Candy",
        es: "Dulces",
        de: "Süßigkeiten",
        fr: "Bonbons",
        it: "Caramelle",
        ja: "キャンディ",
        pt_BR: "Doces",
        ko: "사탕",
        hi: "कैंडी",
        tr: "Şeker",
        ar: "حلوى"
    },
    "cap": {
        en: "Cap",
        es: "Gorra",
        de: "Kappe",
        fr: "Casquette",
        it: "Cappellino",
        ja: "キャップ",
        pt_BR: "Boné",
        ko: "모자",
        hi: "टोपी",
        tr: "Şapka",
        ar: "قبعة"
    },
    "card-games": {
        en: "Card Games",
        es: "Juegos de Cartas",
        de: "Kartenspiele",
        fr: "Jeux de Cartes",
        it: "Giochi di Carte",
        ja: "カードゲーム",
        pt_BR: "Jogos de Cartas",
        ko: "카드게임",
        hi: "कार्ड गेम्स",
        tr: "Kart Oyunları",
        ar: "ألعاب الورق"
    },
    "chair": {
        en: "Chair",
        es: "Silla",
        de: "Stuhl",
        fr: "Chaise",
        it: "Sedia",
        ja: "椅子",
        pt_BR: "Cadeira",
        ko: "의자",
        hi: "कुर्सी",
        tr: "Sandalye",
        ar: "كرسي"
    },
    "children": {
        en: "Children",
        es: "Niños",
        de: "Kinder",
        fr: "Enfants",
        it: "Bambini",
        ja: "子供",
        pt_BR: "Crianças",
        ko: "어린이",
        hi: "बच्चे",
        tr: "Çocuklar",
        ar: "أطفال"
    },
    "desk": {
        en: "Desk",
        es: "Escritorio",
        de: "Schreibtisch",
        fr: "Bureau",
        it: "Scrivania",
        ja: "デスク",
        pt_BR: "Mesa",
        ko: "책상",
        hi: "डेस्क",
        tr: "Masa",
        ar: "مكتب"
    },
    "dessert": {
        en: "Dessert",
        es: "Postre",
        de: "Dessert",
        fr: "Dessert",
        it: "Dolce",
        ja: "デザート",
        pt_BR: "Sobremesa",
        ko: "디저트",
        hi: "मिठाई",
        tr: "Tatlı",
        ar: "حلوى"
    },
    "dress": {
        en: "Dress",
        es: "Vestido",
        de: "Kleid",
        fr: "Robe",
        it: "Vestito",
        ja: "ドレス",
        pt_BR: "Vestido",
        ko: "드레스",
        hi: "पोशाक",
        tr: "Elbise",
        ar: "فستان"
    },
    "electronics": {
        en: "Electronics",
        es: "Electrónicos",
        de: "Elektronik",
        fr: "Électronique",
        it: "Elettronica",
        ja: "電子機器",
        pt_BR: "Eletrônicos",
        ko: "전자제품",
        hi: "इलेक्ट्रॉनिक्स",
        tr: "Elektronik",
        ar: "إلكترونيات"
    },
    "folder": {
        en: "Folder",
        es: "Carpeta",
        de: "Ordner",
        fr: "Dossier",
        it: "Cartella",
        ja: "フォルダー",
        pt_BR: "Pasta",
        ko: "폴더",
        hi: "फ़ोल्डर",
        tr: "Klasör",
        ar: "مجلد"
    },
    "food": {
        en: "Food",
        es: "Comida",
        de: "Essen",
        fr: "Nourriture",
        it: "Cibo",
        ja: "食べ物",
        pt_BR: "Comida",
        ko: "음식",
        hi: "भोजन",
        tr: "Yemek",
        ar: "طعام"
    },
    "frame": {
        en: "Frame",
        es: "Marco",
        de: "Rahmen",
        fr: "Cadre",
        it: "Cornice",
        ja: "フレーム",
        pt_BR: "Moldura",
        ko: "액자",
        hi: "फ्रेम",
        tr: "Çerçeve",
        ar: "إطار"
    },
    "fruit": {
        en: "Fruit",
        es: "Fruta",
        de: "Obst",
        fr: "Fruit",
        it: "Frutta",
        ja: "果物",
        pt_BR: "Fruta",
        ko: "과일",
        hi: "फल",
        tr: "Meyve",
        ar: "فاكهة"
    },
    "furniture": {
        en: "Furniture",
        es: "Muebles",
        de: "Möbel",
        fr: "Meubles",
        it: "Mobili",
        ja: "家具",
        pt_BR: "Móveis",
        ko: "가구",
        hi: "फर्नीचर",
        tr: "Mobilya",
        ar: "أثاث"
    },
    "garage": {
        en: "Garage",
        es: "Garaje",
        de: "Garage",
        fr: "Garage",
        it: "Garage",
        ja: "ガレージ",
        pt_BR: "Garagem",
        ko: "차고",
        hi: "गैराज",
        tr: "Garaj",
        ar: "مرآب"
    },
    "gardening": {
        en: "Gardening",
        es: "Jardinería",
        de: "Garten",
        fr: "Jardinage",
        it: "Giardinaggio",
        ja: "ガーデニング",
        pt_BR: "Jardinagem",
        ko: "원예",
        hi: "बागवानी",
        tr: "Bahçıvanlık",
        ar: "بستنة"
    },
    "glasses": {
        en: "Glasses",
        es: "Gafas",
        de: "Brille",
        fr: "Lunettes",
        it: "Occhiali",
        ja: "メガネ",
        pt_BR: "Óculos",
        ko: "안경",
        hi: "चश्मा",
        tr: "Gözlük",
        ar: "نظارات"
    },
    "grocery-shelf": {
        en: "Grocery Shelf",
        es: "Estante de Comestibles",
        de: "Lebensmittelregal",
        fr: "Étagère d'Épicerie",
        it: "Scaffale Alimentari",
        ja: "食料品棚",
        pt_BR: "Prateleira de Supermercado",
        ko: "식료품 선반",
        hi: "किराना शेल्फ",
        tr: "Market Rafı",
        ar: "رف البقالة"
    },
    "handbag": {
        en: "Handbag",
        es: "Bolso",
        de: "Handtasche",
        fr: "Sac à Main",
        it: "Borsa",
        ja: "ハンドバッグ",
        pt_BR: "Bolsa",
        ko: "핸드백",
        hi: "हैंडबैग",
        tr: "El Çantası",
        ar: "حقيبة يد"
    },
    "hat": {
        en: "Hat",
        es: "Sombrero",
        de: "Hut",
        fr: "Chapeau",
        it: "Cappello",
        ja: "帽子",
        pt_BR: "Chapéu",
        ko: "모자",
        hi: "टोपी",
        tr: "Şapka",
        ar: "قبعة"
    },
    "headphones": {
        en: "Headphones",
        es: "Auriculares",
        de: "Kopfhörer",
        fr: "Casque",
        it: "Cuffie",
        ja: "ヘッドフォン",
        pt_BR: "Fones de Ouvido",
        ko: "헤드폰",
        hi: "हेडफोन",
        tr: "Kulaklık",
        ar: "سماعات رأس"
    },
    "home-decoration": {
        en: "Home Decoration",
        es: "Decoración del Hogar",
        de: "Wohndekoration",
        fr: "Décoration Maison",
        it: "Decorazione Casa",
        ja: "ホームデコレーション",
        pt_BR: "Decoração da Casa",
        ko: "홈 데코레이션",
        hi: "घर की सजावट",
        tr: "Ev Dekorasyonu",
        ar: "ديكور المنزل"
    },
    "hoodie": {
        en: "Hoodie",
        es: "Sudadera con Capucha",
        de: "Kapuzenpullover",
        fr: "Sweat à Capuche",
        it: "Felpa con Cappuccio",
        ja: "フーディー",
        pt_BR: "Moletom com Capuz",
        ko: "후디",
        hi: "हूडी",
        tr: "Kapüşonlu Sweatshirt",
        ar: "هودي"
    },
    "hot-drinks": {
        en: "Hot Drinks",
        es: "Bebidas Calientes",
        de: "Heißgetränke",
        fr: "Boissons Chaudes",
        it: "Bevande Calde",
        ja: "温かい飲み物",
        pt_BR: "Bebidas Quentes",
        ko: "뜨거운 음료",
        hi: "गर्म पेय",
        tr: "Sıcak İçecekler",
        ar: "مشروبات ساخنة"
    },
    "jacket": {
        en: "Jacket",
        es: "Chaqueta",
        de: "Jacke",
        fr: "Veste",
        it: "Giacca",
        ja: "ジャケット",
        pt_BR: "Jaqueta",
        ko: "재킷",
        hi: "जैकेट",
        tr: "Ceket",
        ar: "سترة"
    },
    "jeans": {
        en: "Jeans",
        es: "Vaqueros",
        de: "Jeans",
        fr: "Jean",
        it: "Jeans",
        ja: "ジーンズ",
        pt_BR: "Jeans",
        ko: "청바지",
        hi: "जींस",
        tr: "Kot Pantolon",
        ar: "جينز"
    },
    "kitchen-ware": {
        en: "Kitchen Ware",
        es: "Utensilios de Cocina",
        de: "Küchengeschirr",
        fr: "Ustensiles de Cuisine",
        it: "Utensili da Cucina",
        ja: "キッチン用品",
        pt_BR: "Utensílios de Cozinha",
        ko: "주방용품",
        hi: "रसोई के बर्तन",
        tr: "Mutfak Eşyaları",
        ar: "أدوات المطبخ"
    },
    "lamp": {
        en: "Lamp",
        es: "Lámpara",
        de: "Lampe",
        fr: "Lampe",
        it: "Lampada",
        ja: "ランプ",
        pt_BR: "Lâmpada",
        ko: "램프",
        hi: "लैंप",
        tr: "Lamba",
        ar: "مصباح"
    },
    "laptop": {
        en: "Laptop",
        es: "Portátil",
        de: "Laptop",
        fr: "Ordinateur Portable",
        it: "Laptop",
        ja: "ラップトップ",
        pt_BR: "Laptop",
        ko: "노트북",
        hi: "लैपटॉप",
        tr: "Dizüstü Bilgisayar",
        ar: "حاسوب محمول"
    },
    "lighting": {
        en: "Lighting",
        es: "Iluminación",
        de: "Beleuchtung",
        fr: "Éclairage",
        it: "Illuminazione",
        ja: "照明",
        pt_BR: "Iluminação",
        ko: "조명",
        hi: "प्रकाश व्यवस्था",
        tr: "Aydınlatma",
        ar: "إضاءة"
    },
    "mail": {
        en: "Mail",
        es: "Correo",
        de: "Post",
        fr: "Courrier",
        it: "Posta",
        ja: "郵便",
        pt_BR: "Correio",
        ko: "우편",
        hi: "मेल",
        tr: "Posta",
        ar: "بريد"
    },
    "meat": {
        en: "Meat",
        es: "Carne",
        de: "Fleisch",
        fr: "Viande",
        it: "Carne",
        ja: "肉",
        pt_BR: "Carne",
        ko: "고기",
        hi: "मांस",
        tr: "Et",
        ar: "لحم"
    },
    "medical": {
        en: "Medical",
        es: "Médico",
        de: "Medizinisch",
        fr: "Médical",
        it: "Medico",
        ja: "医療",
        pt_BR: "Médico",
        ko: "의료",
        hi: "चिकित्सा",
        tr: "Tıbbi",
        ar: "طبي"
    },
    "mens-underwear": {
        en: "Men's Underwear",
        es: "Ropa Interior Masculina",
        de: "Herrenunterwäsche",
        fr: "Sous-vêtements Homme",
        it: "Biancheria Intima Uomo",
        ja: "男性用下着",
        pt_BR: "Roupa Íntima Masculina",
        ko: "남성 속옷",
        hi: "पुरुषों का अंडरवियर",
        tr: "Erkek İç Çamaşırı",
        ar: "ملابس داخلية رجالية"
    },
    "monitor": {
        en: "Monitor",
        es: "Monitor",
        de: "Monitor",
        fr: "Moniteur",
        it: "Monitor",
        ja: "モニター",
        pt_BR: "Monitor",
        ko: "모니터",
        hi: "मॉनिटर",
        tr: "Monitör",
        ar: "شاشة"
    },
    "music": {
        en: "Music",
        es: "Música",
        de: "Musik",
        fr: "Musique",
        it: "Musica",
        ja: "音楽",
        pt_BR: "Música",
        ko: "음악",
        hi: "संगीत",
        tr: "Müzik",
        ar: "موسيقى"
    },
    "necklace": {
        en: "Necklace",
        es: "Collar",
        de: "Halskette",
        fr: "Collier",
        it: "Collana",
        ja: "ネックレス",
        pt_BR: "Colar",
        ko: "목걸이",
        hi: "हार",
        tr: "Kolye",
        ar: "عقد"
    },
    "nightgown": {
        en: "Nightgown",
        es: "Camisón",
        de: "Nachthemd",
        fr: "Chemise de Nuit",
        it: "Camicia da Notte",
        ja: "ナイトガウン",
        pt_BR: "Camisola",
        ko: "잠옷",
        hi: "नाइटगाउन",
        tr: "Gecelik",
        ar: "قميص نوم"
    },
    "other": {
        en: "Other",
        es: "Otro",
        de: "Andere",
        fr: "Autre",
        it: "Altro",
        ja: "その他",
        pt_BR: "Outro",
        ko: "기타",
        hi: "अन्य",
        tr: "Diğer",
        ar: "أخرى"
    },
    "outdoor-cooking": {
        en: "Outdoor Cooking",
        es: "Cocina al Aire Libre",
        de: "Outdoor-Küche",
        fr: "Cuisine Extérieure",
        it: "Cucina all'Aperto",
        ja: "アウトドア料理",
        pt_BR: "Cozinha ao Ar Livre",
        ko: "야외 요리",
        hi: "आउटडोर कुकिंग",
        tr: "Açık Hava Yemek Pişirme",
        ar: "طبخ خارجي"
    },
    "pajama": {
        en: "Pajama",
        es: "Pijama",
        de: "Pyjama",
        fr: "Pyjama",
        it: "Pigiama",
        ja: "パジャマ",
        pt_BR: "Pijama",
        ko: "파자마",
        hi: "पजामा",
        tr: "Pijama",
        ar: "بيجامة"
    },
    "paper": {
        en: "Paper",
        es: "Papel",
        de: "Papier",
        fr: "Papier",
        it: "Carta",
        ja: "紙",
        pt_BR: "Papel",
        ko: "종이",
        hi: "कागज",
        tr: "Kağıt",
        ar: "ورق"
    },
    "pets": {
        en: "Pets",
        es: "Mascotas",
        de: "Haustiere",
        fr: "Animaux de Compagnie",
        it: "Animali Domestici",
        ja: "ペット",
        pt_BR: "Animais de Estimação",
        ko: "반려동물",
        hi: "पालतू जानवर",
        tr: "Evcil Hayvanlar",
        ar: "حيوانات أليفة"
    },
    "printer": {
        en: "Printer",
        es: "Impresora",
        de: "Drucker",
        fr: "Imprimante",
        it: "Stampante",
        ja: "プリンター",
        pt_BR: "Impressora",
        ko: "프린터",
        hi: "प्रिंटर",
        tr: "Yazıcı",
        ar: "طابعة"
    },
    "ring": {
        en: "Ring",
        es: "Anillo",
        de: "Ring",
        fr: "Bague",
        it: "Anello",
        ja: "指輪",
        pt_BR: "Anel",
        ko: "반지",
        hi: "अंगूठी",
        tr: "Yüzük",
        ar: "خاتم"
    },
    "scarf": {
        en: "Scarf",
        es: "Bufanda",
        de: "Schal",
        fr: "Écharpe",
        it: "Sciarpa",
        ja: "スカーフ",
        pt_BR: "Cachecol",
        ko: "스카프",
        hi: "स्कार्फ",
        tr: "Atkı",
        ar: "وشاح"
    },
    "seafood": {
        en: "Seafood",
        es: "Mariscos",
        de: "Meeresfrüchte",
        fr: "Fruits de Mer",
        it: "Frutti di Mare",
        ja: "シーフード",
        pt_BR: "Frutos do Mar",
        ko: "해산물",
        hi: "समुद्री भोजन",
        tr: "Deniz Ürünleri",
        ar: "مأكولات بحرية"
    },
    "shirt": {
        en: "Shirt",
        es: "Camisa",
        de: "Hemd",
        fr: "Chemise",
        it: "Camicia",
        ja: "シャツ",
        pt_BR: "Camisa",
        ko: "셔츠",
        hi: "शर्ट",
        tr: "Gömlek",
        ar: "قميص"
    },
    "shoes": {
        en: "Shoes",
        es: "Zapatos",
        de: "Schuhe",
        fr: "Chaussures",
        it: "Scarpe",
        ja: "靴",
        pt_BR: "Sapatos",
        ko: "신발",
        hi: "जूते",
        tr: "Ayakkabı",
        ar: "أحذية"
    },
    "shorts": {
        en: "Shorts",
        es: "Pantalones Cortos",
        de: "Shorts",
        fr: "Short",
        it: "Pantaloncini",
        ja: "ショーツ",
        pt_BR: "Shorts",
        ko: "반바지",
        hi: "शॉर्ट्स",
        tr: "Şort",
        ar: "شورت"
    },
    "smartphone": {
        en: "Smartphone",
        es: "Teléfono Inteligente",
        de: "Smartphone",
        fr: "Smartphone",
        it: "Smartphone",
        ja: "スマートフォン",
        pt_BR: "Smartphone",
        ko: "스마트폰",
        hi: "स्मार्टफोन",
        tr: "Akıllı Telefon",
        ar: "هاتف ذكي"
    },
    "socks": {
        en: "Socks",
        es: "Calcetines",
        de: "Socken",
        fr: "Chaussettes",
        it: "Calzini",
        ja: "靴下",
        pt_BR: "Meias",
        ko: "양말",
        hi: "मोज़े",
        tr: "Çorap",
        ar: "جوارب"
    },
    "sofa": {
        en: "Sofa",
        es: "Sofá",
        de: "Sofa",
        fr: "Canapé",
        it: "Divano",
        ja: "ソファ",
        pt_BR: "Sofá",
        ko: "소파",
        hi: "सोफा",
        tr: "Kanepe",
        ar: "أريكة"
    },
    "soft-drink-or-bottle": {
        en: "Soft Drink or Bottle",
        es: "Refresco o Botella",
        de: "Erfrischungsgetränk oder Flasche",
        fr: "Boisson Gazeuse ou Bouteille",
        it: "Bibita o Bottiglia",
        ja: "ソフトドリンクまたはボトル",
        pt_BR: "Refrigerante ou Garrafa",
        ko: "청량음료 또는 병",
        hi: "शीतल पेय या बोतल",
        tr: "Meşrubat veya Şişe",
        ar: "مشروب غازي أو زجاجة"
    },
    "sports": {
        en: "Sports",
        es: "Deportes",
        de: "Sport",
        fr: "Sports",
        it: "Sport",
        ja: "スポーツ",
        pt_BR: "Esportes",
        ko: "스포츠",
        hi: "खेल",
        tr: "Spor",
        ar: "رياضة"
    },
    "stationery": {
        en: "Stationery",
        es: "Papelería",
        de: "Schreibwaren",
        fr: "Papeterie",
        it: "Cancelleria",
        ja: "文房具",
        pt_BR: "Papelaria",
        ko: "문구류",
        hi: "स्टेशनरी",
        tr: "Kırtasiye",
        ar: "قرطاسية"
    },
    "suit-jacket": {
        en: "Suit Jacket",
        es: "Chaqueta de Traje",
        de: "Sakko",
        fr: "Veste de Costume",
        it: "Giacca da Completo",
        ja: "スーツジャケット",
        pt_BR: "Paletó",
        ko: "정장 재킷",
        hi: "सूट जैकेट",
        tr: "Takım Elbise Ceketi",
        ar: "سترة بدلة"
    },
    "t-shirt": {
        en: "T-Shirt",
        es: "Camiseta",
        de: "T-Shirt",
        fr: "T-Shirt",
        it: "Maglietta",
        ja: "Tシャツ",
        pt_BR: "Camiseta",
        ko: "티셔츠",
        hi: "टी-शर्ट",
        tr: "Tişört",
        ar: "تي شيرت"
    },
    "table": {
        en: "Table",
        es: "Mesa",
        de: "Tisch",
        fr: "Table",
        it: "Tavolo",
        ja: "テーブル",
        pt_BR: "Mesa",
        ko: "테이블",
        hi: "मेज",
        tr: "Masa",
        ar: "طاولة"
    },
    "tablet": {
        en: "Tablet",
        es: "Tableta",
        de: "Tablet",
        fr: "Tablette",
        it: "Tablet",
        ja: "タブレット",
        pt_BR: "Tablet",
        ko: "태블릿",
        hi: "टैबलेट",
        tr: "Tablet",
        ar: "جهاز لوحي"
    },
    "tie": {
        en: "Tie",
        es: "Corbata",
        de: "Krawatte",
        fr: "Cravate",
        it: "Cravatta",
        ja: "ネクタイ",
        pt_BR: "Gravata",
        ko: "넥타이",
        hi: "टाई",
        tr: "Kravat",
        ar: "ربطة عنق"
    },
    "tools": {
        en: "Tools",
        es: "Herramientas",
        de: "Werkzeuge",
        fr: "Outils",
        it: "Strumenti",
        ja: "工具",
        pt_BR: "Ferramentas",
        ko: "도구",
        hi: "उपकरण",
        tr: "Araçlar",
        ar: "أدوات"
    },
    "toys": {
        en: "Toys",
        es: "Juguetes",
        de: "Spielzeug",
        fr: "Jouets",
        it: "Giocattoli",
        ja: "おもちゃ",
        pt_BR: "Brinquedos",
        ko: "장난감",
        hi: "खिलौने",
        tr: "Oyuncaklar",
        ar: "ألعاب"
    },
    "tracksuit": {
        en: "Tracksuit",
        es: "Chándal",
        de: "Trainingsanzug",
        fr: "Survêtement",
        it: "Tuta",
        ja: "トラックスーツ",
        pt_BR: "Agasalho",
        ko: "트랙수트",
        hi: "ट्रैकसूट",
        tr: "Eşofman",
        ar: "بدلة رياضية"
    },
    "trash-can": {
        en: "Trash Can",
        es: "Bote de Basura",
        de: "Mülleimer",
        fr: "Poubelle",
        it: "Cestino",
        ja: "ゴミ箱",
        pt_BR: "Lixeira",
        ko: "쓰레기통",
        hi: "कूड़ादान",
        tr: "Çöp Kutusu",
        ar: "سلة مهملات"
    },
    "trousers": {
        en: "Trousers",
        es: "Pantalones",
        de: "Hose",
        fr: "Pantalon",
        it: "Pantaloni",
        ja: "ズボン",
        pt_BR: "Calças",
        ko: "바지",
        hi: "पतलून",
        tr: "Pantolon",
        ar: "بنطلون"
    },
    "tv": {
        en: "TV",
        es: "Televisión",
        de: "Fernseher",
        fr: "Télévision",
        it: "TV",
        ja: "テレビ",
        pt_BR: "TV",
        ko: "TV",
        hi: "टीवी",
        tr: "TV",
        ar: "تلفزيون"
    },
    "vegetable": {
        en: "Vegetable",
        es: "Verdura",
        de: "Gemüse",
        fr: "Légume",
        it: "Verdura",
        ja: "野菜",
        pt_BR: "Vegetal",
        ko: "채소",
        hi: "सब्जी",
        tr: "Sebze",
        ar: "خضروات"
    },
    "vest": {
        en: "Vest",
        es: "Chaleco",
        de: "Weste",
        fr: "Gilet",
        it: "Giubbotto",
        ja: "ベスト",
        pt_BR: "Colete",
        ko: "조끼",
        hi: "बनियान",
        tr: "Yelek",
        ar: "صدرية"
    },
    "video-game": {
        en: "Video Game",
        es: "Videojuego",
        de: "Videospiel",
        fr: "Jeu Vidéo",
        it: "Videogioco",
        ja: "ビデオゲーム",
        pt_BR: "Videogame",
        ko: "비디오 게임",
        hi: "वीडियो गेम",
        tr: "Video Oyunu",
        ar: "لعبة فيديو"
    },
    "watch": {
        en: "Watch",
        es: "Reloj",
        de: "Uhr",
        fr: "Montre",
        it: "Orologio",
        ja: "腕時計",
        pt_BR: "Relógio",
        ko: "시계",
        hi: "घड़ी",
        tr: "Saat",
        ar: "ساعة"
    },
    "wine-glass": {
        en: "Wine Glass",
        es: "Copa de Vino",
        de: "Weinglas",
        fr: "Verre à Vin",
        it: "Bicchiere da Vino",
        ja: "ワイングラス",
        pt_BR: "Taça de Vinho",
        ko: "와인잔",
        hi: "वाइन ग्लास",
        tr: "Şarap Kadehi",
        ar: "كأس نبيذ"
    },
    "womens-t-shirt": {
        en: "Women's T-Shirt",
        es: "Camiseta de Mujer",
        de: "Damen-T-Shirt",
        fr: "T-Shirt Femme",
        it: "Maglietta da Donna",
        ja: "女性用Tシャツ",
        pt_BR: "Camiseta Feminina",
        ko: "여성용 티셔츠",
        hi: "महिलाओं की टी-शर्ट",
        tr: "Kadın Tişörtü",
        ar: "تي شيرت نسائي"
    },
    "womens-underwear": {
        en: "Women's Underwear",
        es: "Ropa Interior Femenina",
        de: "Damenunterwäsche",
        fr: "Sous-vêtements Femme",
        it: "Biancheria Intima Donna",
        ja: "女性用下着",
        pt_BR: "Roupa Íntima Feminina",
        ko: "여성 속옷",
        hi: "महिलाओं का अंडरवियर",
        tr: "Kadın İç Çamaşırı",
        ar: "ملابس داخلية نسائية"
    },
    "writing-utensil": {
        en: "Writing Utensil",
        es: "Utensilio de Escritura",
        de: "Schreibutensil",
        fr: "Ustensile d'Écriture",
        it: "Strumento di Scrittura",
        ja: "筆記用具",
        pt_BR: "Utensílio de Escrita",
        ko: "필기구",
        hi: "लेखन उपकरण",
        tr: "Yazı Gereçleri",
        ar: "أداة كتابة"
    }
};

/**
 * Get localized name for an icon category
 * @param iconCategory The icon category key (e.g., "t-shirt")
 * @param language The target language code (defaults to browser language or 'en')
 * @returns Localized display name
 */
export function getLocalizedIconCategory(iconCategory: string, language?: string): string {
    // Get browser language or fallback to English
    const browserLanguage = language || (typeof navigator !== 'undefined' ? navigator.language.split('-')[0] : 'en');
    let targetLanguage: SupportedLanguage = 'en';
    
    // Handle Portuguese - map pt to pt_BR
    if (browserLanguage === 'pt' || (typeof navigator !== 'undefined' && navigator.language.startsWith('pt'))) {
        targetLanguage = 'pt_BR';
    } else if (['en', 'es', 'de', 'fr', 'it', 'ja', 'ko', 'hi', 'tr', 'ar'].includes(browserLanguage)) {
        targetLanguage = browserLanguage as SupportedLanguage;
    }

    // Get localized name or fallback to formatted English
    const localization = ICON_CATEGORY_LOCALIZATIONS[iconCategory];
    if (localization) {
        return localization[targetLanguage];
    }

    // Fallback: format the icon category key (replace dashes with spaces, capitalize)
    return iconCategory.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}